"""
Deterministic parser for the orange-data lab "Analytical Report" (English,
generated by eDocEngine VCL). No LLM, no OCR.

    detect(pdf) -> bool
    parse(path) -> dict   # {template, header, detected_residues, _validation}

Layout:
  - inline "Label: value" header (several fields per line), comma decimals
  - results under "Phytosanitary Results  Result LOQ MRL EU ARfD %ARfD",
    grouped by method (TJ019 GC-MS/MS, TJ020 LC-MS/MS) as:
        [-]<name> <result> <loq> <mrl_eu> <arfd> <%arfd>
  - the full screening panel prints substances as "<name> (0,010)"; those lines
    (and method headers ending "(LOQ mg/kg)") are skipped.
"""
import re, sys, json
import pdfplumber

def detect(pdf) -> bool:
    meta = pdf.metadata or {}
    prod = (meta.get("Producer", "") + " " + meta.get("Creator", "")).lower()
    txt = pdf.pages[0].extract_text() or ""
    return "orange-data" in prod or "edocengine" in prod or \
           ("Analytical Report" in txt and "Phytosanitary Results" in txt)

def _lines(pdf):
    out = []
    for pg in pdf.pages:
        out += (pg.extract_text() or "").split("\n")
    return out

def _num(s):
    """Comma- or dot-decimal -> float|None (e.g. '0,051', '5,0')."""
    if s is None: return None
    s = s.strip()
    if not re.match(r"^\d+(?:[.,]\d+)?$", s): return None
    return float(s.replace(".", "").replace(",", ".")) if "," in s else float(s)

HEADER_PATTERNS = {
    "report_number":      r"Report Number\s+(\S+)",
    "report_date":        r"Report date\s+(\d{2}/\d{2}/\d{4})",
    "sample_type":        r"Sample description:\s*(.+?)\s*$",
    "reception_date":     r"Reception date:\s*(\d{2}/\d{2}/\d{4})",
    "analysis_start":     r"Analysis start date:\s*(\d{2}/\d{2}/\d{4})",
    "analysis_end":       r"Analysis end date:\s*(\d{2}/\d{2}/\d{4})",
    "customer_reference": r"CUSTOMER REFERENCE\s+(.+?)\s*$",
}

# a detected row: [-] name  then >= 3 numeric cells (result, loq, mrl_eu[, arfd, %arfd])
ROW_RE = re.compile(
    r"^-?\s*(?P<name>.+?)\s+"
    r"(?P<nums>\d+(?:[.,]\d+)?(?:\s+\d+(?:[.,]\d+)?){2,})\s*$"
)

def parse(path):
    pdf = pdfplumber.open(path)
    if not detect(pdf):
        raise ValueError("Not an orange-data-template report")
    lines = _lines(pdf)

    # --- header ---
    header = {}
    for ln in lines:
        for key, pat in HEADER_PATTERNS.items():
            if key in header: continue
            m = re.search(pat, ln)
            if m: header[key] = m.group(1).strip()
    # client name: the line after the "Report Number ..." line
    for i, ln in enumerate(lines):
        if ln.startswith("Report Number") and i + 1 < len(lines):
            header["client_name"] = lines[i + 1].strip(); break

    # --- detected residues ---
    detected, in_block, tech = [], False, None
    for ln in lines:
        s = ln.strip()
        if s.startswith("Phytosanitary Results"):
            in_block = True; continue
        if not in_block: continue
        if "Technique:" in s:                       # method header
            mt = re.search(r"Technique:\s*([A-Za-z/–-]+MS/MS)", s)
            if mt: tech = mt.group(1)
            continue
        if "(0," in s or "(LOQ" in s or s.startswith("Analysed Compound") \
           or s.startswith("mg/kg"):
            continue                                 # screening panel / units row
        m = ROW_RE.match(s)
        if not m: continue
        nums = [_num(x) for x in m.group("nums").split()]
        nums += [None] * (5 - len(nums))             # pad to result,loq,eu,arfd,%arfd
        detected.append({
            "analyte": m.group("name").strip(" -"),
            "result_mgkg": nums[0],
            "loq_mgkg": nums[1],
            "mrl_eu_mgkg": nums[2],
            "arfd": nums[3],
            "pct_arfd": nums[4],
            "technique": tech,
        })

    errors = []
    if not header.get("report_number"): errors.append("missing report_number")
    if not header.get("sample_type"): errors.append("missing sample_type")
    for r in detected:
        if r["result_mgkg"] is None: errors.append(f"unparsed result for {r['analyte']}")

    return {
        "template": "orangedata-analytical-report",
        "header": header,
        "detected_residues": detected,
        "_validation": {"ok": not errors, "errors": errors, "detected_count": len(detected)},
    }

if __name__ == "__main__":
    for p in sys.argv[1:]:
        print("=" * 70); print(p.split("/")[-1])
        try: print(json.dumps(parse(p), ensure_ascii=False, indent=2))
        except Exception as e: print("  ERROR:", e)
