// Verifies the TS parsers produce the same output as the Python reference.
// Builds a Doc with pdfjs-dist/legacy (Node), runs route(), and deep-diffs
// against the golden JSON generated by the Python parsers.
// Bundle with esbuild (pdfjs-dist external) then run with node.
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import * as fs from 'fs';
import * as path from 'path';
import { route, itemsToWords } from '../src/app/lab-shared/parsers/index';
import type { Doc, Page } from '../src/app/lab-shared/parsers/core';

const SAMPLES = '/Users/tobias/Downloads/sample-reports';
const GOLDEN = process.env.GOLDEN as string;
const FILES = [
  '335 PH LM.085 A 26.PDF', '335 RA2 3.052 A 26.pdf',
  '340 PH LM.L022 A 26_sec 53, 54, 55,56.pdf', '340 RA2 3.018 A 26_sec 53, 54, 55,56.pdf',
  'A5083245-ING.pdf', 'A5085033-ING.pdf', 'A6069815.pdf', 'A6072590.pdf',
  'A6072613.pdf', 'A6078701.pdf',
];

async function loadDocNode(file: string): Promise<Doc> {
  const data = new Uint8Array(fs.readFileSync(file));
  const pdf = await getDocument({ data, useSystemFonts: true } as any).promise;
  let producer = '';
  try {
    const meta: any = await pdf.getMetadata();
    producer = `${meta?.info?.Producer ?? ''} ${meta?.info?.Creator ?? ''}`.trim();
  } catch { /* none */ }
  const pages: Page[] = [];
  for (let i = 1; i <= pdf.numPages; i++) {
    const page = await pdf.getPage(i);
    const height = page.getViewport({ scale: 1 }).height;
    const tc = await page.getTextContent();
    pages.push(itemsToWords(tc.items as any[], height));
  }
  return { producer, pages };
}

function diff(a: any, b: any, p: string, out: string[]): void {
  if (out.length >= 6) return;
  const na = a === undefined ? null : a;
  const nb = b === undefined ? null : b;
  if (typeof na === 'number' && typeof nb === 'number') {
    if (Math.abs(na - nb) > 1e-9) out.push(`${p}: TS=${na} PY=${nb}`);
    return;
  }
  if (na === null || nb === null || typeof na !== 'object') {
    if (na !== nb) out.push(`${p}: TS=${JSON.stringify(na)} PY=${JSON.stringify(nb)}`);
    return;
  }
  if (Array.isArray(na) || Array.isArray(nb)) {
    const la = na?.length ?? 0, lb = nb?.length ?? 0;
    if (la !== lb) { out.push(`${p}.length: TS=${la} PY=${lb}`); return; }
    for (let i = 0; i < la; i++) diff(na[i], nb[i], `${p}[${i}]`, out);
    return;
  }
  const keys = new Set([...Object.keys(na), ...Object.keys(nb)]);
  for (const k of keys) diff(na[k], nb[k], p ? `${p}.${k}` : k, out);
}

async function main() {
  let allPass = true;
  for (const f of FILES) {
    let result: any, err: string | null = null;
    try { result = route(await loadDocNode(path.join(SAMPLES, f))); }
    catch (e: any) { err = String(e?.message ?? e); }
    const golden = JSON.parse(fs.readFileSync(path.join(GOLDEN, `${f}.json`), 'utf8'));
    const out: string[] = [];
    if (err) out.push(`threw: ${err}`);
    else diff(result, golden, '', out);
    const pass = out.length === 0;
    allPass &&= pass;
    const det = result?._validation?.detected_count ?? '?';
    console.log(`[${pass ? 'PASS' : 'FAIL'}] ${f.slice(0, 38).padEnd(38)} ${pass ? `det=${det}` : ''}`);
    for (const d of out) console.log(`        ${d}`);
  }
  console.log(allPass ? '\nAll 10 match the Python golden.' : '\nMismatches above.');
  process.exit(allPass ? 0 : 1);
}
main();
